# Generated by Django 3.1.7 on 2021-03-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(choices=[('Group 1', 'Group 1'), ('Group 2', 'Group 2'), ('Group 3', 'Group 3')], max_length=50),
        ),
    ]
