# Generated by Django 3.1.7 on 2021-03-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210317_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(choices=[('Group_1', 'Group 1'), ('Group_2', 'Group 2'), ('Group_3', 'Group 3')], max_length=50),
        ),
    ]
